#!/usr/bin/env python3
"""Generate the root INDEX.md from every piece's notes.md frontmatter.

Ported from a companion document repo's own scripts/ dir so it can be run
from inside nvim. Operates on the current working directory, not on
wherever this bundle itself is installed — run it (or the nvim
:BuildIndex command that wraps it) from inside the target document repo.

Usage: python3 scripts/build_index.py

Exits non-zero (and writes nothing) if any piece is missing required
frontmatter, printing every problem found to stderr.
"""
import sys
from pathlib import Path

from frontmatter import FrontmatterError, parse

REPO_ROOT = Path.cwd()
TYPE_DIRS = ["articles", "books", "poems", "stories"]
ALLOWED_STATUSES = {"idea", "drafting", "revising", "done"}


def collect_pieces():
    """Return (pieces_by_type, errors). pieces_by_type maps type dir name to
    a sorted list of (slug, title, status)."""
    pieces_by_type = {}
    errors = []

    for type_dir in TYPE_DIRS:
        type_path = REPO_ROOT / type_dir
        if not type_path.is_dir():
            continue

        pieces = []
        for slug_path in sorted(p for p in type_path.iterdir() if p.is_dir()):
            slug = slug_path.name
            notes_path = slug_path / "notes.md"
            rel = f"{type_dir}/{slug}/notes.md"

            if not notes_path.is_file():
                errors.append(f"{rel}: missing notes.md")
                continue

            try:
                fields, _ = parse(notes_path.read_text())
            except FrontmatterError as e:
                errors.append(f"{rel}: {e}")
                continue

            title = fields.get("title", "").strip()
            status = fields.get("status", "").strip()

            if not title:
                errors.append(f"{rel}: missing required 'title' field")
                continue
            if status not in ALLOWED_STATUSES:
                allowed = ", ".join(sorted(ALLOWED_STATUSES))
                errors.append(
                    f"{rel}: 'status' is {status!r}, must be one of: {allowed}"
                )
                continue

            pieces.append((slug, title, status))

        if pieces:
            pieces_by_type[type_dir] = pieces

    return pieces_by_type, errors


def render_index(pieces_by_type):
    lines = [
        "# Index",
        "",
        "<!-- Generated by scripts/build_index.py. Do not edit by hand. -->",
        "",
    ]

    if not pieces_by_type:
        lines.append("_Nothing indexed yet._")
        lines.append("")
        return "\n".join(lines)

    for type_dir in TYPE_DIRS:
        pieces = pieces_by_type.get(type_dir)
        if not pieces:
            continue
        lines.append(f"## {type_dir.capitalize()}")
        lines.append("")
        for slug, title, status in pieces:
            lines.append(f"- [{title}]({type_dir}/{slug}/notes.md) — {status}")
        lines.append("")

    return "\n".join(lines)


def main():
    pieces_by_type, errors = collect_pieces()

    if errors:
        print("build_index: cannot generate INDEX.md, fix the following:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    (REPO_ROOT / "INDEX.md").write_text(render_index(pieces_by_type))
    return 0


if __name__ == "__main__":
    sys.exit(main())
